# Generated by Django 5.1.6 on 2025-02-13 11:08

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ویزگی')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ویزگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=55, verbose_name='توضیح مختصر')),
                ('status', models.BooleanField(default=False, verbose_name='وضیعت')),
                ('position', models.CharField(choices=[('top', 'بالا'), ('middle', 'وسط'), ('button', 'پایین')], default='top', max_length=25, verbose_name='مکان بنر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='store_banne_status_ac2204_idx'), models.Index(fields=['position'], name='store_banne_positio_abf99e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان بنر')),
                ('short_description', models.CharField(blank=True, max_length=55, null=True, verbose_name='توضیحات مختصر بنر')),
                ('file', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1920, 1080], upload_to='images/', verbose_name='')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.banner', verbose_name='بنر')),
            ],
            options={
                'verbose_name': 'تصویر بنر',
                'verbose_name_plural': 'تصویر های بنر',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=30, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحاتـ')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1920, 1080], upload_to='images/', verbose_name='عکس ها')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('material', models.CharField(default='برنجی', max_length=25, verbose_name='حنس')),
                ('inventory', models.IntegerField(default=0, verbose_name='تعداد موجودی')),
                ('sell', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تولید شده در')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('status', models.BooleanField(default=True, verbose_name='وضیعت محصول')),
                ('brand', models.CharField(default='night', max_length=25, verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مجصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[500, 500], upload_to='images/', verbose_name='عکس ها')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ساخته شد در')),
                ('is_main', models.BooleanField(default=False, verbose_name='عکس اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='عکس محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس های محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='اضافه شده در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='محصولات مورد علاقه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصوب',
                'verbose_name_plural': 'محبوب ها',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatherValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='نام محصول')),
                ('feather_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feather_value', to='store.productfeaturename', verbose_name='نام ویزگی')),
            ],
            options={
                'verbose_name': 'مقدار ویزگی',
                'verbose_name_plural': 'مقدار ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('top', 'بالا'), ('middle', 'وسط'), ('button', 'پایین')], default='button', max_length=20)),
                ('product', models.ManyToManyField(to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='اسلاگ')),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='UserCopenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('copen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.copen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'slug'], name='store_categ_name_f50271_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='store_produ_id_2abda1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created', 'updated'], name='store_produ_created_ac8881_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='store_image_created_e9694d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
