# Generated by Django 5.1.6 on 2025-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'ادرس', 'verbose_name_plural': 'ادرس ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ایتم سفارش', 'verbose_name_plural': 'ایتم های سفارش'},
        ),
    ]
